;******************>  Default Structural Data setting    dfstrdat.lsp
(DeFun DefaultStructuralData ()
(SetQ
        DeadLoad                        700.0
        HeightOfColumn                  300.0
        CubeStrengthOfConcrete28        300.0
        StressOfSteel                   1600.0
        %OfSteel                        1.0
        NoOfFloors                      3.0
        StressOfSoil                    2.0
        ThicknessOfPC                   20.0
        WidthOfColumn                   20.0
        PlaneConcreteFoundation         "Yes"
        CType                           "Rect"
        SetDefaultStructuralData          1
        ColBarDiameter                  12.0
        FotBarDiameter                  18.0
)
)
